### 라이브러리 선언

In [ ]:
# 데이터 처리 라이브러리
import pandas as pd

# 데이터 수 계산 라이브러리
import numpy as np

### 데이터 불러오기

In [5]:
featuresData = pd.read_csv("../dataset/feature_regression_example.csv")
featuresData.head(2)

,REGIONID,PRODUCTGROUP,PRODUCT,ITEM,YEARWEEK,YEAR,WEEK,QTY,HOLIDAY,HCLUS,PROMOTION,PRO_PERCENT
0,SEOUL_BANK_001,PG02,PRODUCT0010,ITEM0115,201501,2015,1,1225,Y,1,Y,0.209442
1,SEOUL_BANK_001,PG02,PRODUCT0010,ITEM0115,201502,2015,2,968,N,4,Y,0.209442

In [6]:
featureData

,REGIONID,PRODUCTGROUP,PRODUCT,ITEM,YEARWEEK,YEAR,WEEK,QTY,HOLIDAY,HCLUS,PROMOTION,PRO_PERCENT
0,SEOUL_BANK_001,PG02,PRODUCT0010,ITEM0115,201501,2015,1,1225,Y,1,Y,0.209442
1,SEOUL_BANK_001,PG02,PRODUCT0010,ITEM0115,201502,2015,2,968,N,4,Y,0.209442
2,SEOUL_BANK_001,PG02,PRODUCT0010,ITEM0115,201503,2015,3,1209,N,4,Y,0.208155
3,SEOUL_BANK_001,PG02,PRODUCT0010,ITEM0115,201504,2015,4,1810,Y,2,Y,0.208155
4,SEOUL_BANK_001,PG02,PRODUCT0010,ITEM0115,201505,2015,5,1773,N,4,Y,0.208155
...,...,...,...,...,...,...,...,...,...,...,...,...
100,SEOUL_BANK_001,PG02,PRODUCT0010,ITEM0115,201648,2016,48,2412,Y,0,Y,0.421888
101,SEOUL_BANK_001,PG02,PRODUCT0010,ITEM0115,201649,2016,49,1955,N,4,Y,0.421888
102,SEOUL_BANK_001,PG02,PRODUCT0010,ITEM0115,201650,2016,50,1800,N,4,Y,0.352361
103,SEOUL_BANK_001,PG02,PRODUCT0010,ITEM0115,201651,2016,51,1173,N,4,Y,0.352361
104,SEOUL_BANK_001,PG02,PRODUCT0010,ITEM0115,201652,2016,52,332,Y,1,Y,0.352361

### 1. 타입 통합 및 특성 숫자 컬럼 추가

In [8]:
# 1-1. 타입 통합 (스킵)
# 1-2. 특성 숫자 컬럼 추가
featuresData.HOLIDAY.drop_duplicates()
featuresData["HO_YH"] = np.where( featuresData.HOLIDAY=="Y", 1, 0)
featuresData["PRO_YH"] = np.where( featuresData.PROMOTION=="Y", 1, 0)

### 2. 특성 선정 및 데이터 분리

In [13]:
corrDf = featuresData.corr(numeric_only=True)
stdCorr = 0.3
label = ["QTY"]
features = \
        list( corrDf.loc[ ( abs( corrDf.QTY) > stdCorr ) &  (corrDf.QTY != 1) ].index )
features

print(f"정답지는{label} 문제지는 { features}")

정답지는['QTY'] 문제지는 ['HCLUS', 'PRO_PERCENT', 'HO_YH', 'PRO_YH']

In [ ]:
# 머신러닝 라이브러리
from sklearn.model_selection import train_test_split

In [17]:
# 2-2. 데이터 분리
trainData,testData = train_test_split( featuresData, test_size=0.2, random_state=5 )
print( featuresData.shape )
print( trainData.shape )
print( testData.shape )
trainDataFeatures = trainData.loc[ :, features ]
trainDataLabel = trainData.loc[ :, label]
testDataFeatures = testData.loc[ :, features ]
testDataLabel = testData.loc[:, label ]

(105, 14)
(84, 14)
(21, 14)

### 3. 모델 정의

In [18]:
from sklearn import tree

In [19]:
dtModel = tree.DecisionTreeRegressor()

### 4. 예측

In [ ]:
prdeicValue = fit